# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://www.wxw.moe/@kowaretai"

[social.params]
icon = "brand-mastodon"

[[main]]
name = "主页/Home"
pageRef = "/"
weight = 1

[[main]]
name = "关于我/About"
pageRef = "/page/about"
weight = 10

[[main]]
name = "文字/Posts"
pageRef = "/posts"
weight = 20

[[main]]
name = "留言板/Board"
pageRef = "/page/guestbook"
weight = 40

[[main]]
name = "链接/Links"
pageRef = "/page/links"
weight = 50

[[main]]
name = "RSS"
url = "/index.xml"
weight = 99

