# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://www.wxw.moe/@kowaretai"

[social.params]
icon = "brand-mastodon"

[[main]]
name = "留言板"
pageRef = "/page/guestbook"
weight = 40

[[main]]
name = "RSS"
url = "/index.xml"
weight = 99

